### ISSUE TITLE
Buttons on event page

### ISSUE THREAD

**Issue by tanbrian** [ucsdcirclek/konnection#10]
Clicking the driver, photographer, and writer buttons updates values correctly in the database, but the changes don't reflect in the UI. Also, clicking the signup button more than once in the same event ends up with duplicate registrations.

**Comment by josephnle** [comment]
@tanbrian Fixed the duplicate signups with 8a1964b59bcde8f1eefd71f175eabb5126b3eed2

**Comment by tanbrian** [comment]
Rest of issue fixed with f23a2f72ae7caabe4b0a5bdd1127ab0ab09e9000. The changes not showing up when you hit one of the event buttons (signup, driver, writer, or photographer buttons) was counter-intuitive, so the page refreshes when one of the buttons are clicked. Also modified chair event button to provide a confirmation message first.

**Comment by tanbrian** [comment]
@josephnle I'm considering looking at the Laravel/AngularJS version of the website again since I'm using a lot of Ajax and jQuery, and it gets messy pretty quickly. Also going to have to add a users API to make adding and removing registrations easier via Ajax.
