### ISSUE TITLE
Inconsistent logins

### ISSUE THREAD

**Issue by tanbrian** [ucsdcirclek/konnection#17]
Even when a user has not changed the email or password, logging in sometimes doesn't work, although trying again later with the same credentials results in a successful login. Having difficulty replicating this bug and unsure of what may be causing it.

**Comment by tanbrian** [comment]
At first I thought it was just my computer, but other users have reported being forced to reset the password every time they login because the same credentials do not always work.

**Comment by tanbrian** [comment]
Okay it might have something to do with something in the local/session storage that screws things up when the same user tries to login, because that's really the only thing that can change since logging in does work sometimes.

**Comment by tanbrian** [comment]
Going to go ahead and close this because I haven't ran into this problem for a while. If this turns out to be a problem, then I'll reopen this issue.

**Comment by tanbrian** [comment]
Just kidding, this is for sure still happening. Nothing is printed out to Nginx or Laravel error logs when this happens, so I need to find a way to reproduce this bug.

**Comment by josephnle** [comment]
Might want to check the database passwords to see if they're empty. I changed my email once and I think my password was cleared.

**Comment by tanbrian** [comment]
Thanks for the hint @josephnle! Finally fixed this bug with 0f1c729fe073dc454d4f67c85d6e4c0df1d29cd7. Just for reference, it turned out there were a few issues with the settings page:
* `confirmed` validation rule should be applied to `password` form field instead of `password_confirmation` because the rule expects a matching `_confirmation` field, so even if the user entered matching passwords the site would complain that the user didn't.
* Password wasn't being hashed in `UsersController@update`.

But the "inconsistent logins" thing was happening mainly because of the last issue: users assume that the site won't update fields that they don't enter, which totally makes sense. When they go and update the profile picture, they leave the password fields blank, and when the update form is submitted the empty password fields end up being stored in the database, and the user can't login again because the login page reinforces a minimum password length. Fixed it by using `array_filter` to get rid of empty/null strings.
