### ISSUE TITLE
Multiday events do not span over multiple calendar day boxes

### ISSUE THREAD

**Issue by josephnle** [ucsdcirclek/konnection#18]
A multiday event, such as [Fall Training Conference](http://www.ucsdcki.org/events/fall-training-conference-1) doesn't span across multiple calendar boxes on the calendar.

**Comment by tanbrian** [comment]
Uh is there a reason `end` was set to `event.start_time` instead of `event.end_time`? If not, then I'll just go ahead and close this with aa352982be17b949cb53ffa3c01c0d655ec24442

**Comment by josephnle** [comment]
No idea @tanbrian. Push it and we'll check it out
