### ISSUE TITLE
Add open/close event buttons

### ISSUE THREAD

**Issue by josephnle** [ucsdcirclek/konnection#19]
Add open/close event buttons for admins to quickly be able to open/close events at will

**Comment by tanbrian** [comment]
Trying to avoid studying for finals so  400fe6074b7c89a494b9805925e502bf5d695539.

Quick note: Opening/closing an event sets open/close time to the current time. If updating it this way keeps the open time before the close time, then great. But if opening an event puts the open time before the close time, the close time is set to the event's end time to keep `$event->isOpen()` working.
