### ISSUE TITLE
New members cant upload avatars

### ISSUE THREAD

**Issue by bcvcool** [ucsdcirclek/konnection#22]
Someone made an account and tried changing her avatar and it didnt work

**Comment by tanbrian** [comment]
@bcvcool What do you mean it didn't work? Did the website say that the profile picture was updated when it wasn't, or did a message saying something went wrong pop up?

**Comment by tanbrian** [comment]
Maybe related to #11 , profile picture logic could be off

**Comment by bcvcool** [comment]
I think the former. It wasn't my problem, it was a new member's but she didnt go into much detail sorry

Bradley Ventayen
University of California, San Diego
Neuroscience and Physiology | 2018
UCSD Circle K International Service Chair, 2014-2015
UCSD Circle K International Vice President of Service, 2015-2016

**Comment by tanbrian** [comment]
Refer to #11.
