### ISSUE TITLE
Unlicensed Froala Editor

### ISSUE THREAD

**Issue by reggiewumo** [ucsdcirclek/konnection#36]
Looks ugly in the description boxes

**Comment by josephnle** [comment]
It's because our version of Froala is unlicensed lol. I like it though because it's easy and nice to use. You can use something else that's open source but I made the tradeoff in exchange for ease of use.

**Comment by josephnle** [comment]
New version of TinyMCE isn't too bad if you wanted to switch it out: https://www.tinymce.com
