### ISSUE TITLE
Google Maps integration for events

### ISSUE THREAD

**Issue by josephnle** [ucsdcirclek/konnection#48]
Would be nice to have Google Maps autocomplete for event creation so we can get addresses up.

Additionally, it'd be nice to have the event pages' addresses clickable and linked out to a Google Map somehow.

**Comment by tanbrian** [comment]
OMG yeah having actual addresses would be awesome, especially if we could leverage that for mobile – I'm just imagining how awesome map images would look on an app and how easy it'd be to tap on an event and get directions
